export const FETCH_THEMES_REQUEST = 'FETCH_THEMES_REQUEST';
export const FETCH_THEMES_SUCCESS = 'FETCH_THEMES_SUCCESS';
export const FETCH_THEMES_FAILURE = 'FETCH_THEMES_FAILURE';
export const FETCH_QUEUE_REQUEST = 'FETCH_QUEUE_REQUEST';
export const FETCH_QUEUE_SUCCESS = 'FETCH_QUEUE_SUCCESS';
export const FETCH_QUEUE_FAILURE = 'FETCH_QUEUE_FAILURE';
